# Generated by Django 4.2.10 on 2026-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0040_add_pureblue_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='transcode_status',
            field=models.CharField(choices=[('pending', '转码中'), ('done', '已完成'), ('direct', '免转码直放'), ('failed', '失败')], default='pending', max_length=10, verbose_name='转码状态'),
        ),
    ]
