# Generated by Django 4.2.10 on 2026-10-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0041_alter_music_transcode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_key_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='加密后的 API 密钥'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vault_salt',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='保险箱密码 salt'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vault_verifier',
            field=models.TextField(blank=True, default='', verbose_name='保险箱密码校验串'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='API 密钥（旧版明文，新数据使用加密字段）'),
        ),
    ]
