# Generated by Django 4.2.10 on 2026-10-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0044_downloadrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRecord',
        ),
    ]
