# Generated by Django 4.2.10 on 2026-10-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0045_delete_downloadrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='PdfDocument',
        ),
    ]
