# Generated by Django 4.2.10 on 2026-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0046_delete_music_delete_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='privacy_agreed_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='已同意正文的 SHA-256'),
        ),
    ]
